namespace Dwolla.Checkout
{
    public class DwollaCallback
    {
        /// <summary>Amount of the purchase order formatted to 2 decimal places.</summary>
        public decimal Amount { get; set; }
        
        /// <summary>Order ID provided during the request.</summary>
        public string OrderId { get; set; }
        
        /// <summary>Flagged to 'true' if purchase order for testing purposes only, 'false' otherwise.</summary>
        public bool TestMode { get; set; }
        
        /// <summary>Dwolla transaction ID to identify the successful transaction. If in test mode, the transaction ID has a value of 1.</summary>
        public long TransactionId { get; set; }
        
        /// <summary>Unique purchase order ID generated by Off-Site Gateway.</summary>
        public string CheckoutId { get; set; }
        
        /// <summary>Value of 'Completed' if the transaction was successful. If any errors occured, the status will have a value of 'Failed'.</summary>
        public DwollaCallbackStatus Status { get; set; }
        
        /// <summary>HMAC-SHA1 hexadecimal hash of the CheckoutId and amount ampersand separated using the consumer secret of the application as the hash key.</summary>
        public string Signature { get; set; }
    }

    public enum DwollaCallbackStatus
    {
        Completed = 0x01,
        Failed
    }
}