using System;
using System.Collections.Generic;
using Dwolla.Checkout.Validators;
using FluentValidation;
using FluentValidation.Attributes;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;

namespace Dwolla.Checkout
{
    [Validator(typeof(DwollaCheckoutResponseValidator))]
    public class DwollaCheckoutResponse
    {
        public bool Success { get; set; }

        /// <summary>The error message if the Result is a Failure.</summary>
        public string Message { get; set; }

        /// <summary>The CheckoutId generated by Dwolla used for a URL redirect.</summary>
        public string CheckoutId
        {
            get
            {
                JToken response;
                if( this.AdditionalData.TryGetValue("Response", out response ) )
                {
                    return (response as JObject)?.Property("CheckoutId")?.Value?.Value<string>();
                }
                return null;
            }
        }

        [JsonExtensionData]
        public IDictionary<string, JToken> AdditionalData { get; set; }

        /// <summary>Returns the URL for the customer's browser to complete the checkout process.</summary>
        public string GetRedirectUrl()
        {
            return DwollaServerCheckoutApi.CheckoutUrl.Replace( "{CheckoutId}", this.CheckoutId );
        }

        public DwollaCheckoutResponse()
        {
            this.AdditionalData = new Dictionary<string, JToken>();
        }
    }


}